### PR TITLE
fix(proxy): prevent halting peer subroutines

### LINKED ISSUE #981: Don't block Stream
As pointed out here: https://github.com/radicle-dev/radicle-upstream/pull/967#discussion_r497503768

### PR DESCRIPTION
**Pull request by xla**
The polling of subroutines can starve if the channels are not completely
drained. To remedy that this refactor restructures the internals of the
peer, most notably by have the RunState drive the WaitingRoom
transitions.

* move WaitingRoom into RunState
* use SelectAll for subroutines
* introduce handle for peer control

Fixes #981
Fixes #1009

### CODE REVIEW

**Comment by xla** [comment]
Sorry all, this escalated a bit. The refactor addresses a bunch of concerns, first and foremost the halting subroutines as captured in #981. As the change-set is quite large, it's best to check [subroutine.rs](https://github.com/radicle-dev/radicle-upstream/blob/xla/tame-the-locks/proxy/coco/src/peer/subroutines.rs) for the move to `SelectAll` and [runstate.rs](https://github.com/radicle-dev/radicle-upstream/blob/xla/tame-the-locks/proxy/coco/src/peer/run_state.rs) for the move of the `WaitingRoom`.

@FintanH @geigerzaehler @kim Thanks for all the input and guidance along the way.

@rudolfs The newly introduced [control.rs](https://github.com/radicle-dev/radicle-upstream/blob/xla/tame-the-locks/proxy/coco/src/peer/control.rs) is the way I imagined of how to inspect the state of a running peer.

File: proxy/coco/src/peer/run_state.rs [hunk 1]
```diff
@@ -278,45 +381,87 @@ impl RunState {
...
-        cmds
+                if let Some(urn) = self.waiting_room.next_query(Instant::now()) {
+                    cmds.push(Command::Request(RequestCommand::Query(urn)));
+                }
+                if let Some(url) = self.waiting_room.next_clone() {
+                    cmds.push(Command::Request(RequestCommand::Clone(url)));
+                }
+                cmds
+            },
+            // FIXME(xla): Come up with a strategy for the results returned by the waiting room.
```
Comment (xla) [inline proxy/coco/src/peer/run_state.rs:424]: @FintanH What's ur take on the Results here and how to preserve semantics?

File: proxy/coco/src/peer/control.rs [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+
+use std::time::Instant;
+
+use tokio::sync::{mpsc, oneshot};
+
+use librad::uri::RadUrn;
+
+use crate::request;
+
+/// Reqests sent to the peer.
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/control.rs:11]:
```suggestion
/// Requests sent to the peer.
```

File: proxy/coco/src/peer/control.rs [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+        RadUrn,
+        Instant,
+        oneshot::Sender<Option<request::SomeRequest<Instant>>>,
+    ),
+}
+
+/// Returned responses from the peer.
+#[derive(Debug)]
+pub enum Response {
+    /// Response to a urn request.
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/control.rs:25]:
```suggestion
    /// Response to a `Request::Urn` request.
```

File: proxy/coco/src/peer/subroutines.rs [hunk 4]
```diff
@@ -0,0 +1,280 @@
+//! Management of subroutines.
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:1]: Could you expand this doc? What problems does it address and what should/should NOT go in here would be nice to add

File: proxy/coco/src/peer/subroutines.rs [hunk 5]
```diff
@@ -0,0 +1,280 @@
...
+        RequestInput, RunState, SyncInput, TimeoutInput,
+    },
+    sync, RECEIVER_CAPACITY,
+};
+
+/// Management of "subroutine" tasks.
+#[allow(clippy::missing_docs_in_private_items)]
+pub struct Subroutines {
+    pending_tasks: FuturesUnordered<SpawnAbortable<()>>,
+    inputs: SelectAll<BoxStream<'static, Input>>,
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:41]: Could you document these fields? What is `inputs` and input for? for `pending_tasks`? I'd say no but don't know

File: proxy/coco/src/peer/subroutines.rs [hunk 6]
```diff
@@ -0,0 +1,280 @@
...
+    state: State,
+    store: kv::Store,
+    run_state: RunState,
+
+    input_sender: mpsc::Sender<Input>,
+    subscriber: broadcast::Sender<Event>,
+}
+
+impl Subroutines {
+    /// Constructor.
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:52]:
```suggestion
```

File: proxy/coco/src/peer/subroutines.rs [hunk 7]
```diff
@@ -0,0 +1,280 @@
...
+        state: State,
+        store: kv::Store,
+        run_config: RunConfig,
+        protocol_events: BoxStream<'static, ProtocolEvent<Gossip>>,
+        subscriber: broadcast::Sender<Event>,
+        control_receiver: mpsc::Receiver<control::Request>,
+    ) -> Self {
+        let announce_timer = interval(run_config.announce.interval);
+        let waiting_room_timer = interval(run_config.waiting_room.interval);
+
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:63]:
```suggestion
```

File: proxy/coco/src/peer/subroutines.rs [hunk 8]
```diff
@@ -0,0 +1,280 @@
...
+        let (input_sender, inputs) = mpsc::channel::<Input>(RECEIVER_CAPACITY);
+
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:65]:
```suggestion
```

File: proxy/coco/src/peer/subroutines.rs [hunk 9]
```diff
@@ -0,0 +1,280 @@
...
+        let run_state = RunState::from(run_config);
+
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:67]:
```suggestion
```

File: proxy/coco/src/peer/subroutines.rs [hunk 10]
```diff
@@ -0,0 +1,280 @@
...
+                    return Poll::Ready(Err(e));
+                },
+                Poll::Ready(Some(Ok(()))) => continue,
+                // Either pending, or FuturesUnordered thinks it's done, but
+                // we'll enqueue new tasks below
+                Poll::Ready(None) | Poll::Pending => break,
+            }
+        }
+
+        loop {
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:135]: Could you document this loop?

File: proxy/coco/src/peer/subroutines.rs [hunk 11]
```diff
@@ -0,0 +1,280 @@
...
+            log::error!("announce error: {:?}", err);
+            sender
+                .send(Input::Announce(AnnounceInput::Failed))
+                .await
+                .ok();
+        },
+    }
+}
+
+/// Control response subroutine.
```
Comment (NunoAlexandre) [inline proxy/coco/src/peer/subroutines.rs:202]: These docs don't add much since we already have the module and the fn name. as a reader I'd better like to be informed of what these do and when they are useful.

File: proxy/coco/tests/common.rs [hunk 12]
```diff
@@ -146,6 +138,7 @@ pub fn radicle_project(path: PathBuf) -> project::Create<PathBuf> {
     }
 }
 
+#[allow(dead_code)]
```
Comment (NunoAlexandre) [inline proxy/coco/tests/common.rs:141]: delete?

**Review by NunoAlexandre — COMMENTED** [review]
I like the overall technical decisions :v:

File: proxy/coco/src/peer/subroutines.rs [hunk 13]
```diff
@@ -0,0 +1,280 @@
...
+                // Either pending, or FuturesUnordered thinks it's done, but
+                // we'll enqueue new tasks below
+                Poll::Ready(None) | Poll::Pending => break,
+            }
+        }
+
+        loop {
+            match self.inputs.poll_next_unpin(cx) {
+                Poll::Ready(Some(input)) => {
+                    log::debug!("handling subroutine input: {:?}", input);
```
Comment (geigerzaehler) [inline proxy/coco/src/peer/subroutines.rs:136]: For understanding this method and keeping it focused on the concurrency logic it might be beneficial to extract this block into a separate function.

File: proxy/coco/tests/common.rs (hunk 12 above)
Comment (xla) [reply proxy/coco/tests/common.rs:141]: It's used in the integration tests. Haven't found a way for the compiler not to claim it's dead code.

File: proxy/coco/src/peer/subroutines.rs [hunk 14]
```diff
@@ -0,0 +1,278 @@
...
+    run_state::{
+        AnnounceInput, Command, Config as RunConfig, ControlCommand, Event, Input, RequestCommand,
+        RequestInput, RunState, SyncInput, TimeoutInput,
+    },
+    sync, RECEIVER_CAPACITY,
+};
+
+/// Management of "subroutine" tasks.
+#[allow(clippy::missing_docs_in_private_items)]
+pub struct Subroutines {
```
Comment (geigerzaehler) [inline proxy/coco/src/peer/subroutines.rs:39]: If I understand this structure correctly, it does two things: It handles input events and the business logic around them and it manages tasks and concurrency. Maybe we could separate these two things more clearly. More concretely we could have one logical thread that takes input events and builds futures that are then pushed on a worker to be executed as tasks. The worker would be responsible for spawning tasks and terminating when one of the tasks errors. It would also ensure that all tasks are aborted on an error

File: proxy/coco/src/peer/control.rs [hunk 15]
```diff
@@ -0,0 +1,61 @@
...
+    Urn(
```
Comment (kim) [inline proxy/coco/src/peer/control.rs:26]: Took me a moment to figure out -- nice!

File: proxy/coco/src/request/waiting_room.rs [hunk 16]
```diff
@@ -150,14 +148,14 @@ impl<T, D> WaitingRoom<T, D> {
     ///
     /// If there is no such `urn` then it create a fresh `Request` using the `urn` and `timestamp`
     /// and it will return `None`.
-    pub fn request(&mut self, urn: RadUrn, timestamp: T) -> Option<SomeRequest<T>>
+    pub fn request(&mut self, urn: &RadUrn, timestamp: T) -> Option<SomeRequest<T>>
```
Comment (FintanH) [inline proxy/coco/src/request/waiting_room.rs:151]: Out of curiosity, why change this?

File: proxy/coco/src/peer/run_state.rs [hunk 17]
```diff
@@ -104,11 +156,21 @@ pub enum RequestEvent {
         /// The reason the clone failed.
         reason: String,
     },
+    /// Query the network for the `RadUrn`.
+    Queried(RadUrn),
+    /// A urn was requested.
+    Requested(
+        RadUrn,
+        Instant,
+        Option<oneshot::Sender<Option<SomeRequest<Instant>>>>,
```
Comment (kim) [inline proxy/coco/src/peer/run_state.rs:165]: When can this be `None`?

**Review by kim — COMMENTED** [review]
Nice work!

File: proxy/coco/src/bin/generate-key.rs [hunk 18]
```diff
@@ -0,0 +1,15 @@
+use std::{fs::File, io::prelude::*};
+
+use librad::{keys::SecretKey, peer::PeerId};
+
+fn main() -> Result<(), Box<dyn std::error::Error>> {
```
[the remark this answers is not in the document]
Comment (xla) [reply proxy/coco/src/bin/generate-key.rs:5]: Accidental, deleted it in a follow-up comment.

File: proxy/coco/src/peer/subroutines.rs (hunk 13 above)
Comment (xla) [reply proxy/coco/src/peer/subroutines.rs:136]: To clarify are you suggesting to introduce something like `handle_input` on `Subroutines` to reduce the size of this method body?

File: proxy/coco/src/peer/subroutines.rs (hunk 14 above)
Comment (xla) [reply proxy/coco/src/peer/subroutines.rs:39]: > It handles input events and the business logic around them and it manages tasks and concurrency

The business logic is encapsulated in the `RunState`.

> The worker would be responsible for spawning tasks and terminating when one of the tasks errors. It would also ensure that all tasks are aborted on an error

What you describe is the `Subroutines` responsibility already, I don't see what an extra worker abstraction would add to this.

Comment (kim) [reply proxy/coco/src/peer/subroutines.rs:39]: If by "business logic" you mean the morphism `Command -> SpawnAbortable`, then yeah, I also thought about how this could be abstracted out. It's not so obvious how to capture the parameters though (namely `state` and `store`), sans partial application. (Did someone say `TaskFactoryImpl`?)

File: proxy/coco/src/peer/run_state.rs [hunk 19]
```diff
@@ -42,44 +57,83 @@ pub enum Command {
...
+    PeerSynced(PeerId),
+    /// Request fullfilled with a successful clone.
+    RequestCloned(RadUrl),
+    /// Requested urn was queried on the network.
+    RequestQueried(RadUrn),
+    /// Waiting room interval ticked.
+    RequestTick,
+}
+
+impl MaybeFrom<&Input> for Event {
```
[the remark this answers is not in the document]
Comment (FintanH) [reply proxy/coco/src/peer/run_state.rs:100]: Are we using `MaybeFrom` in any other places? _Maybe_ we just need a function :shrug:

File: proxy/coco/src/peer/run_state.rs (hunk 17 above)
Comment (xla) [reply proxy/coco/src/peer/run_state.rs:165]: We call it a lot when we don't care about the answer, namely in the tests.

File: proxy/coco/src/peer/run_state.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (xla) [reply proxy/coco/src/peer/run_state.rs:100]: Went down that path, but it feels an abuse. It's not the same semantics. I can drop the `trait` if we feel strongly about it.

File: proxy/coco/src/peer/run_state.rs (hunk 1 above)
Comment (FintanH) [reply proxy/coco/src/peer/run_state.rs:424]: A very important `Error` result here is the `TimedOut` variant. We will likely want to communicate that back. I'm almost thinking that we could just communicate the `Result` back on the channel so that the endpoint can also communicate that error.

What do you think?

Comment (xla) [reply proxy/coco/src/peer/run_state.rs:424]: Could you expand which of the calls below returns `TimedOut`? Sounds almost more important to react to the returns inline here and change the state machine semantics. Currently the only input that carries a channel is the `Requested` variant.

File: proxy/coco/src/peer/subroutines.rs (hunk 14 above)
Comment (xla) [reply proxy/coco/src/peer/subroutines.rs:39]: Could we expand for what we are optimising for? Do we want to be able to test this code block in isolation? Are we keen to find static guarantees for the `Command -> SpawnAbortable` mapping?

There is already quite a lot of infrastructure involved to run the peer machinery which tips the noise-to-signal ratio unfavourably, so any more of it should give us sick gains.

File: proxy/coco/src/peer/run_state.rs (hunk 1 above)
Comment (FintanH) [reply proxy/coco/src/peer/run_state.rs:424]: > Could you expand which of the calls below returns TimedOut?

`queired` and `cloning` do -- check out their docs

> Sounds almost more important to react to the returns inline here and change the state machine semantics. Currently the only input that carries a channel is the Requested variant.

Ah right, wasn't thinking through fully. It's more like that we'll want to report the `TimedOut` errors when we hook up notifications -- as well as the successful cases of "found peer" and "cloned repo".

On top of that, logging warnings could be useful to know when we're requesting things with the wrong state transitions.

File: proxy/coco/src/request/waiting_room.rs (hunk 16 above)
Comment (xla) [reply proxy/coco/src/request/waiting_room.rs:151]: It was inconsistent with the other methods. Was there a semantic significance to expect a value instead of a reference?

Comment (FintanH) [reply proxy/coco/src/request/waiting_room.rs:151]: I can't remember :sweat_smile: Thanks for making it more consistent :+1:

File: proxy/coco/src/peer/subroutines.rs (hunk 14 above)
Comment (kim) [reply proxy/coco/src/peer/subroutines.rs:39]: Extensibility. If you want to add a new command, you need to change code in at least three places, one of which is `poll` -- which should not at all change, but the reviewer will have to look at the diff to convince herself of this being the case.

Comment (kim) [reply proxy/coco/src/peer/subroutines.rs:39]: I guess moving the pattern match to an inherent method would be good enough for that

Comment (xla) [reply proxy/coco/src/peer/subroutines.rs:39]: a087b84

File: proxy/coco/src/peer/subroutines.rs [hunk 20]
```diff
@@ -0,0 +1,278 @@
...
+                    return Poll::Ready(Err(e));
+                },
+                Poll::Ready(Some(Ok(()))) => continue,
+                // Either pending, or FuturesUnordered thinks it's done, but
+                // we'll enqueue new tasks below
+                Poll::Ready(None) | Poll::Pending => break,
+            }
+        }
+
+        loop {
```
[the remark this answers is not in the document]
Comment (xla) [reply proxy/coco/src/peer/subroutines.rs:172]: I have not forgotten https://github.com/radicle-dev/radicle-upstream/pull/1009#discussion_r501277948 - can you think of a way to reliably trigger that case, so we can assert the hand-wired `wake_by_ref` operates as we like?

[the remark this answers is not in the document]
Comment (kim) [reply proxy/coco/src/peer/subroutines.rs:172]: How do you mean that? I'm not sure there is a way to build a test case around this. But actually we can ask `FuturesUnordered::is_empty`, so all we need is to conditionally wake on that in the `Poll::Pending` branch.

[the remark this answers is not in the document]
Comment (xla) [reply proxy/coco/src/peer/subroutines.rs:172]: fce40f5


dunno what I'm doing

File: proxy/coco/src/peer/subroutines.rs (hunk 14 above)
Comment (geigerzaehler) [reply proxy/coco/src/peer/subroutines.rs:39]: > If by "business logic" you mean the morphism `Command -> SpawnAbortable`, then yeah, I also thought about how this could be abstracted out.

Yes, this is (almost) what I meant. I was talking about `Command -> impl Future`.

> Could we expand for what we are optimising for?

Separation of concerns. The concurrency/worker logic is not easy to understand follow, so keeping it separate aids that. Moreover we could write tests for the worker more easily. Don’t let this be a blocker, though.

File: proxy/coco/src/peer/run_state.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (geigerzaehler) [reply proxy/coco/src/peer/run_state.rs:100]: I’d strongly favor removing this abstraction but will leave it up to you.

[the remark this answers is not in the document]
Comment (FintanH) [reply proxy/coco/src/peer/run_state.rs:100]: I'd second that because it's only used in one place. If you wanted to abstract we could do our favourite impl trick!
```
impl From<&Input> for Option<Event>`
```

[the remark this answers is not in the document]
Comment (FintanH) [reply proxy/coco/src/peer/run_state.rs:100]: Oh wait, no you can't

File: proxy/coco/src/peer/gossip.rs [hunk 21]
```diff
@@ -0,0 +1,36 @@
...
+            urn: urn.clone(),
+            rev: Some(Rev::Git((*rev).into())),
+            origin: None,
+        })
+        .await;
+}
+
+/// Emit a [`Gossip`] request for the given `urn`.
+///
+/// # Errors
```
Comment (FintanH) [inline proxy/coco/src/peer/gossip.rs:24]: There are no errors :eyes:

File: proxy/coco/src/peer/run_state.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (xla) [reply proxy/coco/src/peer/run_state.rs:100]: @FintanH I tried that, dunno how to call `from` correctly with that impl.

**Review by FintanH — COMMENTED** [review]
One moooore thing

File: proxy/coco/src/peer/run_state.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (FintanH) [reply proxy/coco/src/peer/run_state.rs:100]: Ya, I was wrong anyway because we can't impl `From`/Into` for `Option`

File: proxy/coco/src/peer/subroutines.rs [hunk 22]
```diff
@@ -0,0 +1,299 @@
...
+                    for cmd in self.run_state.transition(input) {
+                        let task = self.spawn_command(cmd);
+
+                        self.pending_tasks.push(task);
+                    }
+                },
+                Poll::Ready(None) => return Poll::Ready(Ok(())),
+                Poll::Pending => {
+                    if !self.pending_tasks.is_empty() {
+                        cx.waker().wake_by_ref()
```
Comment (geigerzaehler) [inline proxy/coco/src/peer/subroutines.rs:191]: I believe this will make the executor spin and repeatedly poll this future. Let’s assume we have one task in `self.pending_tasks` that is blocked by IO and will return `Poll::Pending` for the next couple of seconds. Let’s also assume that there are now inputs arriving on `self.inputs`. If you follow the code in this method if will always break out of the first loop that calls `self.pending_tasks.poll_next_unpin(cx)` and land here. Since we are calling the waker, the task that runs this future will schedule the `poll()` here to be called again. This brings us back to the begining. And since nothing has changed (we’re still waiting on IO from the other task) we will be stuck in a loop.

The code wants to address the following issue

>  Once self.inputs returns Pending and we did enqueue new tasks, we should summon the waker before returning Pending.

This is handled by `FuturesUnordered`. We are passing the context to `FuturesUnordered::poll_next_unpin()`. If one of the tasks in `self.pending_tasks` finishes, `FuturesUnordered` will call the waker which ensures that this future is polled again.

File: proxy/coco/src/peer/subroutines.rs [hunk 23]
```diff
@@ -0,0 +1,299 @@
...
+                        self.subscriber.send(event).ok();
+                    }
+
+                    for cmd in self.run_state.transition(input) {
+                        let task = self.spawn_command(cmd);
+
+                        self.pending_tasks.push(task);
+                    }
+                },
+                Poll::Ready(None) => return Poll::Ready(Ok(())),
```
Comment (geigerzaehler) [inline proxy/coco/src/peer/subroutines.rs:188]: Is it correct that we want to abort all running tasks once the input stream stops?

File: proxy/coco/src/peer/subroutines.rs (hunk 22 above)
Comment (kim) [reply proxy/coco/src/peer/subroutines.rs:191]: I don't think your reasoning is correct:

a. There is no "make the executor spin" -- calling `wake_by_ref` puts us on the back of the poll queue, nothing more. Iow, its semantics is "yield".
b. Morally, we **want** to recurse here, because our `FuturesUnordered` was most likely empty before we entered the second `loop` -- ie. it returned `Ready` from being polled. However, since we **know** that we enqueued new tasks, we must ensure that we are polled again soonish, in order to poll the inputs queue.
c. If there are no new inputs **nor** have enqueued new tasks, we don't wake -- because there's nothing new we can expect when polled again. So, we only return `Pending`.

File: proxy/coco/src/peer/subroutines.rs (hunk 23 above)
Comment (kim) [reply proxy/coco/src/peer/subroutines.rs:188]: I think so, because the only way the stream can signal `Ready` is because all the channels the `SelectAll` is closing over return `Ready`. This can only happen when all their senders have been dropped.

File: proxy/coco/src/peer/subroutines.rs (hunk 22 above)
Comment (kim) [reply proxy/coco/src/peer/subroutines.rs:191]: Oh I see, we want to distinguish between `Pending` and `Ready` as the result of polling the `FuturesUnordered` -- it it was `Pending`, it wasn't empty before.

Comment (geigerzaehler) [reply proxy/coco/src/peer/subroutines.rs:200]: The second part of my analysis was wrong. If `pending_tasks.poll_next_unpin()` returns `Poll::Ready(None)` we will need to ensure that `Subroutine::poll` will be called again if we push an item to `pending_tasks`. This is because `FuturesUnordered` will not wake up any task when the pushed future finishes. I guess this was the point that you made, @kim.

> Oh I see, we want to distinguish between `Pending` and `Ready` as the result of polling the `FuturesUnordered` -- it it was `Pending`, it wasn't empty before.

Indeed. It is exactly this case that makes the executor spin. The executor will poll every future on its queue and these polls are inexpensive and don’t block. So even if we are at the back and there are a lot of other futures queued we will call `Subroutine::poll` again pretty quickly. And if nothing has changed (in contrast to `yield`) we will put the future on the queue again.

Comment (xla) [reply proxy/coco/src/peer/subroutines.rs]: eeacd3c

File: proxy/coco/src/peer/subroutines.rs (hunk 23 above)
Comment (geigerzaehler) [reply proxy/coco/src/peer/subroutines.rs:203]: I’m just wondering whether we want to wait for all the tasks to be finished.

File: proxy/coco/src/peer/run_state.rs [hunk 24]
```diff
@@ -199,29 +284,59 @@ impl From<Config> for RunState {
             config,
             connected_peers: HashSet::new(),
             status: Status::Stopped(Instant::now()),
+            waiting_room: WaitingRoom::new(waiting_room::Config::default()),
```
Comment (FintanH) [inline proxy/coco/src/peer/run_state.rs:287]: The default here will set the delta to `0` because I believe that's the default for `Duration`. We should probably define `Duration` that makes more sense as a `const` to set it as, or pass it from the `Config`.

**Review by kim — DISMISSED** [review]
image

File: proxy/coco/src/peer/run_state.rs [hunk 25]
```diff
@@ -199,29 +284,59 @@ impl From<Config> for RunState {
...
 impl RunState {
     /// Constructs a new state.
     #[cfg(test)]
-    const fn new(config: Config, connected_peers: HashSet<PeerId>, status: Status) -> Self {
+    fn new(config: Config, connected_peers: HashSet<PeerId>, status: Status) -> Self {
         Self {
             config,
             connected_peers,
             status,
+            waiting_room: WaitingRoom::new(waiting_room::Config::default()),
```
Comment (FintanH) [inline proxy/coco/src/peer/run_state.rs:300]: But then this one is safe I would say because it's useful to have no delta during testing.

**Review by FintanH — COMMENTED** [review]
Sorry, should have spotted this one sooner

File: proxy/coco/src/peer/run_state.rs (hunk 24 above)
Comment (xla) [reply proxy/coco/src/peer/run_state.rs]: fe90e77

**Review by geigerzaehler — APPROVED** [review]

**Review by FintanH — APPROVED** [review]
:ship: it

**Comment by kim** [comment]
> I’m just wondering whether we want to wait for all the tasks to be
> finished.

Initially, I wrote this to poll the task results queues only once, but that
risks missing events from expiring timers -- in that case, we may not have any
pending tasks, nor pushed any new ones. So, we'd just return `Pending`, and
there's no way to know for the runtime that it should wake _our_ poll when a new
event is available.

It is potentially that this "subroutine" loop is just not a good fit for async
Rrrrrrrust -- there isn't really a reason to yield back to the executor unless
all in-flight tasks are blocked on IO, or we hit the circumstance that there's
no input to react to (neither from outside triggers nor timers). In a sane
environment, one would implement this thing simply as an OS thread, and never
care about whether it blocks.
