### PR TITLE
fix(ui): transaction center should hide when clicking outside

### LINKED ISSUE #517: Transactions list should collapse when clicking outside of it
close transactions by closing outside

### PR DESCRIPTION
**Pull request by cloudhead**
Closes #517

### CODE REVIEW

File: ui/DesignSystem/Component/Transaction/Center.svelte [hunk 1]
```diff
@@ -47,7 +56,12 @@
   }
 </style>
 
-<div class="center" class:negative data-cy="transaction-center">
+<svelte:window on:click={handleClick} />
+<div
+  class="center"
+  bind:this={txList}
```
Comment (xla) [inline ui/DesignSystem/Component/Transaction/Center.svelte:62]:
```suggestion
  bind:this={txList}
  class="center"
```
