### PR TITLE
fix(proxy): do not drop event tasks

### LINKED ISSUE #1191: Project state changes aren't automatically reflected in UI
Steps to reproduce:

1. get a projectID from http://seedling.radicle.xyz
2. open Upstream and search for the project <kbd>⌘</kbd>+<kbd>p</kbd> and paste in the projectID
3. click the `Follow` button
4. the project should appear in the "Still looking..." part of the "Following" tab
  Screenshot 2020-11-05 at 09 35 42

5. we can observe in the proxy logs that the project is being fetched from the network already:
```
 INFO  librad::git::storage  > Storage::clone_repo; local.id=hyyrm4b99tw66akyupqquzsmd5qigyfikgqazpw9s8emn36wmwgymg url=rad+git://hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw/hwd1yrebwu63acutrtjd7jq7fa34y589sct67hf94b96jtnnuo15bb54h8o/
 INFO  quinn::connection     > drive; id=0
 INFO  quinn::connection     >
 INFO  librad::git::types    > creating symbolic ref refs/namespaces/hwd1yrebwu63acutrtjd7jq7fa34y589sct67hf94b96jtnnuo15bb54h8o/refs/rad/ids/hwd1yreyyshcoykq3urf7g1bx1x69ar84mgmuc6zmskqm3et4erneh8q3fa -> refs/namespaces/hwd1yreyyshcoykq3urf7g1bx1x69ar84mgmuc6zmskqm3et4erneh8q3fa/refs/rad/id
 INFO  librad::git::storage  > creating symbolic link: refs/namespaces/hwd1yrebwu63acutrtjd7jq7fa34y589sct67hf94b96jtnnuo15bb54h8o/refs/rad/self -> refs/namespaces/hwd1yrens9ar3d6gdc1oj3xdr9f87mz7dt68m3ey45thcggn5xg5sx3fwpo/refs/rad/id
 INFO  librad::git::types    > creating symbolic ref refs/namespaces/hwd1yrebwu63acutrtjd7jq7fa34y589sct67hf94b96jtnnuo15bb54h8o/refs/rad/self -> refs/namespaces/hwd1yrens9ar3d6gdc1oj3xdr9f87mz7dt68m3ey45thcggn5xg5sx3fwpo/refs/rad/id
 INFO  quinn::connection     > drive; id=0
```

**Expected outcome:** the screen should automatically refresh and show the now followed project

**Actual outcome:** no refresh is happening, we still see the "Still looking..." area

When I manually refresh the app via <kbd>⌘</kbd>+<kbd>r</kbd> the project appears:

Screenshot 2020-11-05 at 09 38 43

### LINKED ISSUE #1208: Network activity indicator is not updated automatically
When Upstream is started, the network activity indicator icon is stuck in the "syncing" state indefinitely.
It should reflect the actual connectivity state.

Screenshot 2020-11-09 at 15 21 51

When refreshing the app manually, it shows the correct state:

Screenshot 2020-11-09 at 15 24 57

It seems like a regression somewhere in SSE event handling.

Related to: https://github.com/radicle-dev/radicle-upstream/issues/1191.

### PR DESCRIPTION
**Pull request by MeBrei**
Closes #1191
Closes #1208

Only the initial event (set up in the `local_peer_event` endpoint) was sent to the event stream. All subsequent events were not broadcasted since the tasks in `run_rigging` (process.rs) were immediately dropped.

### CODE REVIEW

File: proxy/coco/src/spawn_abortable.rs [hunk 1]
```diff
@@ -26,6 +26,7 @@ pub enum Error {
 /// Stop-gap until we can abort [`JoinHandle`]s directly:
 /// tokio-rs@cbb14a7bb9a13363e1abee8caff2bad1f996c263
 #[allow(clippy::missing_docs_in_private_items)]
+#[must_use]
```
Comment (geigerzaehler) [inline proxy/coco/src/spawn_abortable.rs:29]: We could maybe add a hint why the value needs to be used with `#[must_use = "..."]`.

File: proxy/api/src/process.rs [hunk 2]
```diff
@@ -112,7 +112,7 @@ async fn run_rigging(
 
     if let Some(seeds_sender) = seeds_sender {
         let seeds_store = ctx.store().clone();
-        coco::SpawnAbortable::new(async move {
+        let _seeds_event_task = coco::SpawnAbortable::new(async move {
```
Comment (xla) [inline proxy/api/src/process.rs:115]: This should be awaited in the select down below, then we don't run into the same issue again in the future.

**Review by xla — CHANGES_REQUESTED** [review]
Great find!

**Review by geigerzaehler — APPROVED** [review]

File: proxy/api/src/process.rs [hunk 3]
```diff
@@ -110,38 +114,13 @@ async fn run_rigging(
...
-                }
-
-                last_seeds = seeds;
-            }
-        });
-    }
-
     let subscriptions = notification::Subscriptions::default();
     let peer_subscriptions = subscriptions.clone();
+    let seeds_store = ctx.store().clone();
```
Comment (xla) [inline proxy/api/src/process.rs:119]: Think this belongs in the block where the seeds_sender is deconstructed.

**Review by xla — APPROVED** [review]
Dope!

🌯 ™️ 🌘 🖌

**Review by xla — APPROVED** [review]
📊 🐕 📴 🤖

**Review by geigerzaehler — APPROVED** [review]
