### PR TITLE
fix(proxy): extensive validation

### LINKED ISSUE #822: Create project from existing repo deletes your master branch
Using this git config, trying to create a rad project from this repo will nuke the master branch and fail to create the rad remotes.

```
[core]
	bare = false
	repositoryformatversion = 0
	filemode = true
	logallrefupdates = true
[remote "rad"]
	url = file:///home/cloudhead/.local/share/radicle/git/
	fetch = +refs/namespaces/hwd1yrenyw7wymtmxams3rwcemk73chydfjpinji86yqjywawjeu31d7b6c/refs/heads/*:refs/heads/*
	push = +refs/heads/*:refs/namespaces/hwd1yrenyw7wymtmxams3rwcemk73chydfjpinji86yqjywawjeu31d7b6c/refs/heads/*
[remote "origin"]
	url = git@github.com:cloudhead/popol.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

### LINKED ISSUE #1135: Validate existing repository setup
The PR https://github.com/radicle-dev/radicle-upstream/pull/1134 is a good start for ensuring paths are valid. I think it would be good to continue along this vein and validate things if we want to create an existing repository.

At least two things come to mind:
* Check that the specified default branch exists
* Check that if a rad remote exists then see if the URLs match

### PR DESCRIPTION
**Pull request by FintanH**
Fixes #1135
Fixes #822 

* Pushed all validation logic into `project::create::validation`
* A `Repo` must be now validated into a `validation::Repository` which has passed the checks
* Then a working copy can be safely set up (we check for the validations again, just to be sure)

### CODE REVIEW

File: proxy/coco/src/project/create/validation.rs [hunk 1]
```diff
@@ -0,0 +1,299 @@
...
+    )]
+    MissingDefaultBranch {
+        /// The repository path we're setting up.
+        repo_path: PathBuf,
+        /// The default branch that was expected to be found.
+        branch: String,
+    },
+
+    /// The `rad` remote was found but it did not have a URL.
+    #[error("the `rad` exists but is missing its url field")]
```
Comment (xla) [inline proxy/coco/src/project/create/validation.rs:52]:
```suggestion
    #[error("the `rad` remote exists but is missing its url field")]
```

**Review by xla — APPROVED** [review]
Berry Bope!

🌐 📳 📃 ⏫

**Comment by rudolfs** [comment]
This introduces a change in behaviour, when creating a project from an existing repository that was previously added to radicle we now get an error:

Screenshot 2020-11-05 at 09 14 11

Before this we were be able to add such repositories: https://github.com/radicle-dev/radicle-upstream/issues/621.

Is this on purpose? Is @radicle-dev/product aware of this change?

**Comment by FintanH** [comment]
@rudolfs: That feature can lead to this "feature" https://github.com/radicle-dev/radicle-upstream/issues/822 :stuck_out_tongue_closed_eyes: 

This is at least possible to troubleshoot:
* `cd <existing project>
* `git remote rename rad old-rad`
* Retry creating project

If this is an issue, then I think it's worth discussing some solutions.

File: proxy/coco/src/keystore.rs [hunk 2]
```diff
@@ -108,10 +108,10 @@ impl Keystorage<Memory> {
 }
 
 /// Synonym for an error when interacting with a file-backed store for [`librad::keys`].
-type FileError = file::Error<SecretBoxError<Infallible>, keys::IntoSecretKeyError>;
```
Comment (FintanH) [inline proxy/coco/src/keystore.rs:111]: Note that I made these `pub` because `cargo doc` started complaining. I see no harm in them being public

File: proxy/coco/src/keystore.rs [hunk 3]
```diff
@@ -108,10 +108,10 @@ impl Keystorage<Memory> {
...
+pub type FileError = file::Error<SecretBoxError<Infallible>, keys::IntoSecretKeyError>;
```
Comment (geigerzaehler) [inline proxy/coco/src/keystore.rs:111]: Why do we need to make this type public? I couldn’t find any reference to it

**Comment by rudolfs** [comment]
@FintanH yeah, I assumed we would be doing the rename of the old remote automatically, as you commented here: https://github.com/radicle-dev/radicle-upstream/issues/822#issuecomment-683925262, so the behaviour for users wouldn't change. Would that be possible?

File: proxy/coco/src/state.rs [hunk 4]
```diff
@@ -967,87 +968,4 @@ mod test {
 
         Ok(())
     }
-
-    #[tokio::test]
-    async fn create_with_existing_remote_with_reset() -> Result<(), Box<dyn std::error::Error>> {
```
Comment (geigerzaehler) [inline proxy/coco/src/state.rs:972]: Are we replacing these tests with something?

File: proxy/coco/src/keystore.rs (hunk 3 above)
Comment (FintanH) [reply proxy/coco/src/keystore.rs:111]: The `cargo doc` command started complaining in CI: https://github.com/radicle-dev/radicle-upstream/pull/1190#pullrequestreview-524064290

File: proxy/coco/src/state.rs (hunk 4 above)
Comment (FintanH) [reply proxy/coco/src/state.rs:972]: I outlined why I removed them in the commit message https://github.com/radicle-dev/radicle-upstream/pull/1190/commits/ee3c24bf3232cd09edb31c4ce115c58352cd3596. Let me know if you have any questions about it :)

**Comment by FintanH** [comment]
> @FintanH yeah, I assumed we would be doing the rename of the old remote automatically, as you commented here: #822 (comment), so the behaviour for users wouldn't change. Would that be possible?

I think it's not a good idea to move things from under a user, even if we did create it in the first place. Another solution might be to uniquely name the `rad` remote, for example `<my user>@<my peer id>`. 

> Also the current error message is unreadable, because it's too long for the notification. But I guess #1187 will take care of that.

:grimacing:

File: proxy/coco/src/keystore.rs (hunk 3 above)
Comment (geigerzaehler) [reply proxy/coco/src/keystore.rs:111]: Sorry, didn’t see your comment

**Review by rudolfs — APPROVED** [review]
Fine by me as long as the workaround for https://github.com/radicle-dev/radicle-upstream/pull/1190#issuecomment-722222115 is documented in http://docs.radicle.xyz/understanding-radicle/troubleshooting . 👍

**Review by geigerzaehler — APPROVED** [review]

File: proxy/coco/src/keystore.rs (hunk 3 above)
Comment (FintanH) [reply proxy/coco/src/keystore.rs:111]: No worries, concurrency is hard :smile:
