### PR TITLE
fix(ui): update source browsing

### LINKED ISSUE #762: Fix scrollbars on source code view
We should style these scrollbars to something that looks good.

2020-08-07-153605_816x1052_scrot

### PR DESCRIPTION
**Pull request by juliendonck**
- Fixes weird scrollbars on source browsing -> closes #762
- adds markdown support for all markdown files
- fixes markdown styling

### CODE REVIEW

File: ui/DesignSystem/Component/SourceBrowser/FileSource.svelte [hunk 1]
```diff
@@ -1,8 +1,9 @@
 <script>
   import { format } from "timeago.js";
   import { link } from "svelte-spa-router";
+  import { isMarkdown } from "../../../src/source.ts";
```
Comment (xla) [inline ui/DesignSystem/Component/SourceBrowser/FileSource.svelte:4]:
```suggestion

  import { isMarkdown } from "../../../src/source.ts";
```
