### PR TITLE
fix(ui): open only one modal at a time

### LINKED ISSUE #1417: shortcuts: when navigating to settings via shortcuts it doesn't hide modal
When having a modal open and the user navigates to the settings page via the shortcut the modal is not closed.

### PR DESCRIPTION
**Pull request by MeBrei**
Closes #1417 

Any opened modal or the design system guide will be closed if another one is opened via shortcuts.

### CODE REVIEW

File: ui/Hotkeys.svelte [hunk 1]
```diff
@@ -48,6 +48,13 @@
 
     if (!shortcut) return;
 
+    // Close any opened modal, before openening the next one.
+    modal.hide();
```
Comment (xla) [inline ui/Hotkeys.svelte:52]: This leads to a slight flicker, it might be more effective to move this logic into the toggle and only hide the modal if the new destination isn't one.

**Review by xla — CHANGES_REQUESTED** [review]

File: ui/Hotkeys.svelte (hunk 1 above)
Comment (MeBrei) [reply ui/Hotkeys.svelte:52]: For me the flicker only happens, when I have a modal opened and the switch to a fullscreen (settings or design system guide). I don't see a flicker when switching between modals.
For the case modal-fullscreen case I guess we have to decide on the order, either close modal than navigate (that is how it is now) or first navigate and then close the modal.

Comment (xla) [reply ui/Hotkeys.svelte:52]: Sorry the case where we navigate to a fullscreen page is the case I meant. The second option you layed out seems reasonable and is what I tried to say with checking if it is a modal that we navigate to before hiding.

**Review by xla — APPROVED** [review]
🎓 👆 😊 ☁️

**Review by rudolfs — APPROVED** [review]
Looks good to me.

One thing that we could maybe improve is the settings toggle.

To me, it makes sense for modals (fullscreen like the design system or overlays), but having the settings screen toggleable always feelt weird.

If I press <kbd>⌘</kbd>+<kbd>,</kbd> it jumps between settings and the previous screen I was on.

Not sure if it's in the scope of this PR though.

**Comment by MeBrei** [comment]
> Looks good to me.
> 
> One thing that we could maybe improve is the settings toggle.
> 
> To me, it makes sense for modals (fullscreen like the design system or overlays), but having the settings screen toggleable always felt weird.
> 
> If I press ⌘+, it jumps between settings and the previous screen I was on.
> 
> Not sure if it's in the scope of this PR though.

Moved it into a new issue #1435
