### PR TITLE
fix: handle missing source object gracefully

### LINKED ISSUE #934: Fix error message when switching between branches
Steps to reproduce:

1. create a new project from an existing repository, use this repo as source: https://github.com/radicle-dev/git-platinum
2. check out the `dev` branch `git checkout dev`
3. push the branch to Radicle: `git push rad`
4. open the Upstream UI and go to the platinum project
5. select the `dev` branch in the revision selector
6. select the file `here-we-are-on-a-dev-branch.lol`
7. switch to the `master` branch in the revision selector

Expected to see an informative message in the UI, that this file is not available on the selected branch, instead got this error message:
Screenshot 2020-09-18 at 15 41 03

The error on the proxy side looks like this:
```
 ERROR api::http::error      > Rejection(Coco(PathNotFound(Path(NonEmpty { head: Label { label: "here-we-are-on-a-dev-branch.lol", hidden: false }, tail: [] }))))
```

Refs https://github.com/radicle-dev/radicle-upstream/issues/544.

### PR DESCRIPTION
**Pull request by xla**
Closes #934

### CODE REVIEW

**Comment by xla** [comment]
@brandonhaslegs @juliendonck Could you provide input of what the source browsing view should present when a file could not be found.

File: proxy/api/src/http/error.rs [hunk 1]
```diff
@@ -100,6 +100,11 @@ pub async fn recover(err: Rejection) -> Result<impl Reply, Infallible> {
                         "GIT_ERROR",
                         format!("Internal Git error: {:?}", git_error),
                     ),
+                    coco::Error::PathNotFound(path) => (
+                        StatusCode::NOT_FOUND,
+                        "NOT_FOUND",
+                        format!("object not found under '{}'", path),
```
Comment (rudolfs) [inline proxy/api/src/http/error.rs:106]: I think the message could be a bit more user-friendly, since the only object we currently allow the user to navigate to via the UI is a file, it could read:

"File /{} not found on the current branch"

Currently it looks like this.
Screenshot 2020-09-21 at 09 12 16

Comment (xla) [reply proxy/api/src/http/error.rs:106]: Waiting for input see https://github.com/radicle-dev/radicle-upstream/pull/937#issuecomment-695008704

Comment (cloudhead) [reply proxy/api/src/http/error.rs:106]: I think something like:

File `<file>` was not found on `<branch>`

.. would do it

**Comment by brandonhaslegs** [comment]
In Figma: https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=5304%3A7663

In PNG:
File not on this branch

**Comment by NunoAlexandre** [comment]
@xla can we get an update on this?

**Comment by xla** [comment]
Gonan get to it after #992.

File: ui/DesignSystem/Component/EmptyState.svelte [hunk 2]
```diff
@@ -29,12 +30,16 @@
     align-items: center;
     height: calc(100vh - var(--bigheader-height));
     text-align: center;
-    max-width: 20rem;
+    max-width: 30rem;
```
Comment (NunoAlexandre) [inline ui/DesignSystem/Component/EmptyState.svelte:33]: This would be better defined using vw for improved responsiveness but won't make it a blocker.

**Review by NunoAlexandre — APPROVED** [review]
