### PR TITLE
fix(proxy): validate creation paths

### LINKED ISSUE #1118: Broken project state when creating project with existing name
Reproduce with:

1. New project
2. Create a new repository
3. Choose a path which has an existing project in it
4. Use an existing project name
5. Create project

You should get "Incorrect input" and the project dashboard doesn't work.

### PR DESCRIPTION
**Pull request by FintanH**
Fixes #1118 

We don't want to create a radicle project and its working copy if it fails
validation criteria since we can't rollback that creation. In this change,
we make sure that a path is validated before finishing the attempt to
create the radicle project and its working copy.

### CODE REVIEW

**Comment by FintanH** [comment]
Please review, in the meantime I'm fixing clippers

**Comment by FintanH** [comment]
I think validating an existing repository with things like default branch checks and remote checks would be a good idea. I think I'll create another issue for that.

**Review by rudolfs — APPROVED** [review]

**Review by cloudhead — APPROVED** [review]
Very nice!

File: proxy/coco/src/project/create.rs [hunk 1]
```diff
@@ -18,6 +15,27 @@ use radicle_surf::vcs::git::git2;
 
 use crate::{config, user::User};
 
+/// Validation Errors
+pub mod validation {
```
Comment (NunoAlexandre) [inline proxy/coco/src/project/create.rs:19]: namespacing ftw :ok_hand:

File: proxy/coco/src/project/create.rs [hunk 2]
```diff
@@ -18,6 +15,27 @@ use radicle_surf::vcs::git::git2;
...
+    pub enum Error {
+        /// The path already existed when trying to create a new project.
+        #[error("the path provided '{0}' already exists")]
+        AlreadExists(PathBuf),
+
+        /// The path was expected to exist already but does not.
+        #[error("the path provided '{0}' does not exist when it was expected to")]
+        PathDoesNotExist(PathBuf),
+
+        /// The path was expected to point to a git repository but it did not.
```
Comment (NunoAlexandre) [inline proxy/coco/src/project/create.rs:33]: Shouldn't this be git-agnostic? :thinking:

File: proxy/coco/src/project/create.rs [hunk 3]
```diff
@@ -75,16 +93,61 @@ impl<Path: AsRef<path::Path>> Repo<Path> {
...
+    fn full_path(&self) -> PathBuf {
+        match self {
+            Self::Existing { path } => path.to_path_buf(),
+            Self::New { name, path } => path.join(name),
+        }
+    }
+}
+
+/// A `Repo` that has passed through validation, using [`Repo::validate`].
+pub struct ValidatedRepo(Repo);
```
Comment (NunoAlexandre) [inline proxy/coco/src/project/create.rs:148]: This is nice :ok_hand:

File: proxy/coco/src/state/error.rs [hunk 4]
```diff
@@ -28,6 +28,10 @@ pub enum Error {
     #[error(transparent)]
     Create(#[from] crate::project::create::Error),
 
+    /// An error occurred while validating the path for creating a project.
+    #[error(transparent)]
+    CreateValidation(#[from] crate::project::create::validation::Error),
```
Comment (NunoAlexandre) [inline proxy/coco/src/state/error.rs:33]: So now we have `Error::Create` and `CreateValidation`. I was expecting the creation to validate, i.e, that these were blent. Can you help me understand?

**Review by NunoAlexandre — COMMENTED** [review]
Solid :call_me_hand: 

Just a few questions

File: proxy/api/src/http/error.rs [hunk 5]
```diff
@@ -109,6 +109,30 @@ pub async fn recover(err: Rejection) -> Result<impl Reply, Infallible> {
...
+                    ) => (
+                        StatusCode::NOT_FOUND,
+                        "PATH_DOES_NOT_EXIST",
+                        coco::project::create::validation::Error::PathDoesNotExist(path.clone())
+                            .to_string(),
+                    ),
+                    coco::state::Error::CreateValidation(
+                        coco::project::create::validation::Error::NotARepo(path),
+                    ) => (
+                        StatusCode::NOT_FOUND,
```
Comment (xla) [inline proxy/api/src/http/error.rs:131]: A `400` might communicate the error better.

File: proxy/coco/src/project/create.rs [hunk 6]
```diff
@@ -51,22 +69,22 @@ pub enum Error {
 /// The data required to either open an existing repository or create a new one.
 #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
 #[serde(rename_all = "camelCase", tag = "type")]
-pub enum Repo<Path> {
```
Comment (xla) [inline proxy/coco/src/project/create.rs:54]: fantomas

File: proxy/coco/src/project/create.rs [hunk 7]
```diff
@@ -75,16 +93,61 @@ impl<Path: AsRef<path::Path>> Repo<Path> {
...
+                // TODO(finto): This may be too permissive. Need to look into git errors.
+                if git2::Repository::open(path.clone()).is_err() {
+                    return Err(validation::Error::NotARepo(path));
+                }
+
+                Ok(ValidatedRepo(Self::Existing { path }))
+            },
+            Self::New { name, path } => {
+                let repo_path = path.join(name.clone());
+                if repo_path.exists() {
```
Comment (xla) [inline proxy/coco/src/project/create.rs:129]: Is this not too strict? An empty directory should be valid for a new repo, or am I misunderstanding?

File: proxy/coco/src/project/create.rs [hunk 8]
```diff
@@ -144,29 +208,41 @@ impl<Path: AsRef<path::Path>> Repo<Path> {
...
-    /// How the repository should be created or opened.
-    pub repo: Repo<Path>,
+    /// The [`Repo`] to create with. It's left as a generic parameter so that we can have
+    /// `Create<Repo>` and `Create<ValidatedRepo>` for that sweet type safety.
+    pub repo: R,
 }
 
-impl<Path: AsRef<path::Path>> Create<Path> {
+impl Create<Repo> {
+    #![allow(clippy::use_self)]
```
Comment (xla) [inline proxy/coco/src/project/create.rs:227]:
```suggestion
#[allow(clippy::use_self)]
impl Create<Repo> {
```

File: proxy/coco/src/project/create.rs [hunk 9]
```diff
@@ -144,29 +208,41 @@ impl<Path: AsRef<path::Path>> Repo<Path> {
...
+    /// Validate `Create<Repo>` into a `Create<ValidatedRepo>`. This ensures that we have valid
+    /// paths when we attempt to create the working copy.
+    ///
+    /// It needs to be called before using [`Create::setup_repo`].
```
Comment (xla) [inline proxy/coco/src/project/create.rs:231]: What happens if isn't called before?

**Review by xla — CHANGES_REQUESTED** [review]
QUALITY :clap: OF :clap: LAIF

Couple of things inside.

File: proxy/api/src/http/error.rs (hunk 5 above)
Comment (FintanH) [reply proxy/api/src/http/error.rs:131]: Word, I was torn between the two :+1:

File: proxy/coco/src/project/create.rs (hunk 8 above)
Comment (FintanH) [reply proxy/coco/src/project/create.rs:227]: Why scope it to the whole `impl` rather than the single function?

File: proxy/coco/src/project/create.rs (hunk 9 above)
Comment (FintanH) [reply proxy/coco/src/project/create.rs:231]: You can't :smiling_imp: Types, yo

File: proxy/coco/src/project/create.rs (hunk 2 above)
Comment (FintanH) [reply proxy/coco/src/project/create.rs:33]: I dunno how I can make it git agnostic unless you have some suggestions

File: proxy/coco/src/state/error.rs (hunk 4 above)
Comment (FintanH) [reply proxy/coco/src/state/error.rs:33]: The idea was to separate the validation and creation. But you have a point it should happen at both points really.

File: proxy/coco/src/project/create.rs (hunk 6 above)
Comment (FintanH) [reply proxy/coco/src/project/create.rs:54]: :innocent:

File: proxy/coco/src/project/create.rs (hunk 7 above)
Comment (FintanH) [reply proxy/coco/src/project/create.rs:129]: Good shout :+1:

**Review by xla — APPROVED** [review]
📖 🍻 🐛 🚣

**Review by cloudhead — APPROVED** [review]
