### PR TITLE
fix(ui): only one overlay open at a time

### LINKED ISSUE #648: Prevent more than one overlay from being open at a time
Opening one overlay/dropdown should close any other overlays/dropdowns that are currently open. In addition to preventing overlapping, it's just standard behavior.

- [ ] Org members page 
image
- [ ] Project page
image
- [ ] Project page
image

Maybe there are other instances of this, but this is the one I noticed.

### PR DESCRIPTION
**Pull request by sarahscott**
- [x] singleton store for overlays/dropdowns
- [x] straightforward wrapper component

clicks
clickss

Fixes #648

### CODE REVIEW

File: ui/DesignSystem/Component/SourceBrowser/ClickOutside.svelte [hunk 1]
```diff
@@ -0,0 +1,17 @@
+<script lang="ts">
+  import { openDropdown, currentlyOpen } from "../../../src/dropdown";
+
+  let container;
+  export let shouldOpen = false;
```
Comment (sarahscott) [inline ui/DesignSystem/Component/SourceBrowser/ClickOutside.svelte:5]: ideally components will use this as a wrapper & expand/close based on `shouldOpen`

**Comment by rudolfs** [comment]
Nice progress @sarahscott! Have a look at my findings: https://github.com/radicle-dev/radicle-upstream/pull/966.

**Review by rudolfs — APPROVED** [review]
This is really neat!! 🚀 
Everything works like it should, couldn't find any edge cases or bugs.

Didn't realise you could put a component into a store, quite ingenious!

**Review by NunoAlexandre — DISMISSED** [review]
neat work, Sarah :100:

File: ui/DesignSystem/Component/AdditionalActionsDropdown.svelte [hunk 2]
```diff
@@ -1,9 +1,13 @@
...
+<script lang="ts">
   import { fade } from "svelte/transition";
 
   import { Icon } from "../Primitive";
+
+  import Overlay from "./Overlay.svelte";
   import Urn from "./Urn.svelte";
   import Tooltip from "./Tooltip.svelte";
+  import type { SvelteComponent } from "svelte";
+  import { CSSPosition } from "../../src/style";
```
Comment (xla) [inline ui/DesignSystem/Component/AdditionalActionsDropdown.svelte:10]:
```suggestion
<script lang="ts">
  import { fade } from "svelte/transition";
  import type { SvelteComponent } from "svelte";

  import { CSSPosition } from "../../src/style";
  
  import { Icon } from "../Primitive";
  import Overlay from "./Overlay.svelte";
  import Tooltip from "./Tooltip.svelte";
  import Urn from "./Urn.svelte";
```

File: ui/DesignSystem/Component/AdditionalActionsDropdown.svelte [hunk 3]
```diff
@@ -21,10 +25,18 @@
     item.event();
   };
 
-  export let dataCy = null;
-  export let style = null;
-  export let menuItems = null;
-  export let headerTitle = null;
+  export let menuItems: {
```
Comment (xla) [inline ui/DesignSystem/Component/AdditionalActionsDropdown.svelte:28]: Could probably be pushed into a ts file and reused wherever we render meus.

File: ui/src/overlay.ts [hunk 4]
```diff
@@ -0,0 +1,13 @@
+import { derived, writable } from "svelte/store";
+import { SvelteComponent } from "svelte";
```
Comment (xla) [inline ui/src/overlay.ts:2]:
```suggestion
import { SvelteComponent } from "svelte";
import { derived, writable } from "svelte/store";
```

File: ui/src/overlay.ts [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+
+const currentlyOpenStore = writable<SvelteComponent | undefined>(undefined);
+export const currentlyOpen = derived(currentlyOpenStore, store => store);
```
Comment (xla) [inline ui/src/overlay.ts:5]:
```suggestion
const currentStore = writable<SvelteComponent | undefined>(undefined);
export const current= derived(currentStore, store => store);
```

File: ui/src/overlay.ts [hunk 6]
```diff
@@ -0,0 +1,13 @@
...
+
+export const openOverlay = (component: SvelteComponent) => {
+  currentlyOpenStore.set(component);
+};
```
Comment (xla) [inline ui/src/overlay.ts:9]:
```suggestion
export const open = (component: SvelteComponent) => {
  currentStore.set(component);
};
```

File: ui/src/overlay.ts [hunk 7]
```diff
@@ -0,0 +1,13 @@
...
+
+export const closeOverlay = () => {
+  currentlyOpenStore.set(undefined);
+};
```
Comment (xla) [inline ui/src/overlay.ts:13]:
```suggestion
export const close = () => {
  currentStore.set(undefined);
};
```

**Review by xla — APPROVED** [review]
Very dope! Left some suggestions, no blockers.

🍵 🔎 🔏 ⏹

**Comment by rudolfs** [comment]
Accidentally merged `master` into this branch without realising it was based off of `sos/more-typing`, undid that change in a force push. Sorry for messing with your PR!

**Comment by rudolfs** [comment]
There was a regression introduced in: https://github.com/radicle-dev/radicle-upstream/pull/963/commits/f9f447ac6c7753a0f5e7702e0b60372f8b964229. Instead of calling `close()` from `overlay.ts`, `window.close()` got called, causing the app to close unexpectedly.

Fixed in: https://github.com/radicle-dev/radicle-upstream/pull/963/commits/16b2da03aec1e42777f79183e64754c9f6404ed0.

reg

**Review by rudolfs — DISMISSED** [review]

**Comment by NunoAlexandre** [comment]
> There was a regression introduced in: [f9f447a](https://github.com/radicle-dev/radicle-upstream/commit/f9f447ac6c7753a0f5e7702e0b60372f8b964229). Instead of calling `close()` from `overlay.ts`, `window.close()` got called, causing the app to close unexpectedly.
> 
> Fixed in: [16b2da0](https://github.com/radicle-dev/radicle-upstream/commit/16b2da03aec1e42777f79183e64754c9f6404ed0).
> 
> reg

We should test this :ballot_box_with_check:

File: ui/DesignSystem/Component/AdditionalActionsDropdown.svelte (hunk 3 above)
Comment (sarahscott) [reply ui/DesignSystem/Component/AdditionalActionsDropdown.svelte:28]: For now I think this is fine because the type-checker will throw an error if this is used incorrectly by a parent component.

**Review by NunoAlexandre — APPROVED** [review]
nice :smiley:

**Review by rudolfs — APPROVED** [review]

**Review by NunoAlexandre — APPROVED** [review]
