### PR TITLE
fix(proxy): persist TimedOut state

### LINKED ISSUE #1023: Timeout transition
Turns out that I didn't transition the state when timing out, but just return an error: https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/coco/src/request/waiting_room.rs#L225-L228.

We should insert the updated state and _then_ return the `Err`.

### PR DESCRIPTION
**Pull request by FintanH**
Fixes #1023 

We never persisted the TimedOut state when we encountered one, instead
returning it directly as an error.
This PR fixes that by first persisting the TimedOut state during a
transition and then returning it as an error. We can confirm the
persistence in the test cases for when we reach a timeout.

### CODE REVIEW

File: proxy/coco/src/request/waiting_room.rs [hunk 1]
```diff
@@ -183,14 +181,16 @@ impl<T, D> WaitingRoom<T, D> {
...
-                    },
-                    Either::Left(mismatch) => Err(Error::StateMismatch((&mismatch).into())),
-                }
+            Some(request) => match request.clone().transition(matcher, transition) {
+                Either::Right(Either::Right(next)) => {
+                    self.requests.insert(urn.id.clone(), next.into());
+                    Ok(())
+                },
+                Either::Right(Either::Left(timeout)) => {
+                    self.requests.insert(urn.id.clone(), timeout.clone().into());
```
Comment (cloudhead) [inline proxy/coco/src/request/waiting_room.rs:190]: Does this list every shrink?

Comment (FintanH) [reply proxy/coco/src/request/waiting_room.rs:190]: Not yet: https://github.com/radicle-dev/radicle-upstream/issues/956

**Review by xla — APPROVED** [review]
(*^ω^*)

**Review by xla — APPROVED** [review]
🎲 🐑 ⚰ 🐼

**Review by cloudhead — APPROVED** [review]
