### PR TITLE
chore(ui): bug fixing

### LINKED ISSUE #327: Add placeholder images
Think of a consistent way to show placeholder images in the app.

- [x] binary content
- [x] when there's no readme
- [x] other places in the app where we use plant image.

### LINKED ISSUE #733: Spinner should spin
The input spinner should maybe actually spin (screenshot but would look the same as a gif):

Screen Shot 2020-07-31 at 7 01 16 PM

In recent specs it looks a little different too:

Screen Shot 2020-07-31 at 7 02 08 PM

### LINKED ISSUE #744: Hovering over "Register project" should show a register handle tooltip
On the project page.

Similar to the register handle to create an org tooltip.
image

But this one should say "Register your handle to register this project".

image

### LINKED ISSUE #746: Fix layout of seeds section in settings
- [x] Change layout to have text on the left and the field on the right.
image
---
- [x] remove field height change on hover
seed-field-hover
---
- [x] add underline to `Learn about seeds` link

### PR DESCRIPTION
**Pull request by juliendonck**
- fixes spinner not spinning -> closes #733 
- adds binary content placeholder -> closes #327 
- fix settings seed input -> closes #746 
- fix tooltip on greyed out dropdown item -> closes #744

### CODE REVIEW

File: ui/DesignSystem/Primitive/Icon/Spinner.svelte [hunk 1]
```diff
@@ -19,7 +17,15 @@
   }
 </style>
 
-<IconWrapper on:click {dataCy} {style}>
+<svg
```
Comment (rudolfs) [inline ui/DesignSystem/Primitive/Icon/Spinner.svelte:20]: Perhaps adding a comment here would make sense so we don't refactor this away by accident sometime in the future.

Comment (juliendonck) [reply ui/DesignSystem/Primitive/Icon/Spinner.svelte:21]: https://github.com/radicle-dev/radicle-upstream/pull/747/commits/51c08645f61459a2d8d9dd77c2c6b377ee1d9296
