### PR TITLE
Copy: Fix text in settings

### LINKED ISSUE #1327: Change `users` to `people` in Settings
Replace the Seed subheader in `Settings:

_Seeds help you find more projects and users on the network._

with

_Seeds help you find more projects and people on the network._

The reasoning:

After discussing with @kim , we should change the language around seeds to correctly reflect the distinction between `persons` and `users`. The thinking is as follows (recording for my sake):

A `peer` is essentially a machine, and can be anonymous. It's basically a set of keys.

A `peer` becomes a `person` when it associates an identity to its keys, thus allowing it to associate metadata to said identity (which is the personal identity document)

`user` will be the correct terminology for describing a `person` who has created an identity via a client (right now, Upstream). They are a `user` because they have associated application-specific metadata to their personal identity document. 

So ` people` is the correct term for _what_ a seed node helps an Upstream user to discover, as seed nodes can track `persons`  that _aren't_ associated with an application. `People` is a superset of users & persons. 

Hope this is clear!

### PR DESCRIPTION
**Pull request by juliendonck**
closes #1327 
Signed-off-by: Julien Donck <hello@juliendonck.com>

### CODE REVIEW

**Review by brandonhaslegs — APPROVED** [review]

**Comment by brandonhaslegs** [comment]
Should we also change other instances of `user` to `people`?

**Comment by brandonhaslegs** [comment]
Edit remotes modal:
- [ ] `Add a user’s Device ID to collaborate with them on this project.`

Token Streams:
- [ ] `Add receivers to your outgoing support by clicking the “Support” button on user profiles. You can also add any Ethereum address to your Stream.`
- [ ] `Your support is paused. To resume, make sure you have enough balance and a montly budget set to be split amongst the users you support.`

File: ui/Modal/ManagePeers.svelte [hunk 1]
```diff
@@ -82,7 +82,7 @@
     <Emoji emoji={"💻"} size="huge" style="margin-bottom: 1.5rem;" />
     <h1>Edit remotes</h1>
     <p style="margin-top: 0.5rem; color: var(--color-foreground-level-6);">
-      Add a user’s Device ID to collaborate with them on this project.
+      Add a person's Device ID to collaborate with them on this project.
```
Comment (brandonhaslegs) [inline ui/Modal/ManagePeers.svelte:85]:
```suggestion
      Add someone’s Device ID to collaborate with them on this project.
```

File: ui/Screen/Wallet/Pool/Outgoing/Support.svelte [hunk 2]
```diff
@@ -247,8 +247,8 @@
         {#if poolData.receivers.size === 0}
           <p>
             Add receivers to your outgoing support by clicking the “Support”
-            button on user profiles. You can also add any Ethereum address to
-            your Stream.
+            button on people's profiles. You can also add any Ethereum address
```
Comment (brandonhaslegs) [inline ui/Screen/Wallet/Pool/Outgoing/Support.svelte:250]:
```suggestion
            button on someone’s profile. You can also add any Ethereum address
```
