### PR TITLE
fix: on invalid passphrase clear and refocus input

### LINKED ISSUE #1179: Improve unlock screen
- on unsuccessful unlock
  - [ ] (re-)focus on the passphrase input
  - [ ] select the value of the passphrase input

### PR DESCRIPTION
**Pull request by geigerzaehler**
When the user types in an invalid passphrase we clear the input and refocus it.

Fixes #1179

### CODE REVIEW

**Review by brandonhaslegs — APPROVED** [review]
works for me

File: ui/Screen/Lock.svelte [hunk 1]
```diff
@@ -6,20 +6,48 @@
...
       unlockInProgress = true;
-      await session.unseal(passphrase).finally(() => {
+      try {
+        const unlocked = await session.unseal(passphrase);
+        if (!unlocked) {
+          passphrase = "";
+          // We wait until the component has re-rendered with
+          // `unlockInProgress = false` and the input has been enabled
+          // again.
+          svelteTick().then(() => {
```
Comment (rudolfs) [inline ui/Screen/Lock.svelte:36]: For my own understanding: is there a reason why we don't `await` here instead of `.then`?

File: ui/DesignSystem/PasswordInput.svelte [hunk 2]
```diff
@@ -6,35 +6,43 @@
...
   const dispatch = createEventDispatcher();
 
   // Can't use normal `autofocus` attribute on the `input`:
   // "Autofocus processing was blocked because a document's URL has a fragment"
-  // preventScroll is necessary for onboarding animations to work.
-  $: if (autofocus) {
-    inputElement && inputElement.focus({ preventScroll: true });
-  }
+  onMount(() => {
+    console.log({ autofocus, inputElement });
```
[the remark this answers is not in the document]
Comment (geigerzaehler) [reply ui/DesignSystem/PasswordInput.svelte:40]: https://github.com/radicle-dev/radicle-upstream/pull/2149

File: ui/Screen/Lock.svelte (hunk 1 above)
Comment (geigerzaehler) [reply ui/Screen/Lock.svelte:36]: If we `await` `svelteTick`, then `unlockInProgress` will be set to `false` _after_ the svelte tick. This would defeat the purpose of using `svelteTick`.
