### PR TITLE
fix: show commit count on project page

### LINKED ISSUE #924: Show commit count based on revision
The commit tab currently shows the number of commits from the project stats. Instead the number of commits on the selected revision should be shown.

### PR DESCRIPTION
**Pull request by MeBrei**
* extends the commit endpoint with stats
* shows the correct commit count of the selected peer and branch
* cleans up the variables project page components

Note: Changing the selected peer can't be tested right now.

Closes #924 

**TODO**
- [x] fix source browsing test
- [x] fix jumpy horizontal header (jump between no-count & count)

### CODE REVIEW

**Comment by rudolfs** [comment]
Found a bug, where switching between projects doesn't reload the revision selector properly.

branch

File: proxy/api/src/http/source.rs [hunk 1]
```diff
@@ -729,10 +730,11 @@ mod test {
         })?;
 
         http::test::assert_response(&res, StatusCode::OK, |have| {
-            assert_eq!(have, json!(want));
-            assert_eq!(have.as_array().unwrap().len(), 14);
+            assert_eq!(have["headers"], json!(want.headers));
+            assert_eq!(have["headers"].as_array().unwrap().len(), 14);
```
Comment (FintanH) [inline proxy/api/src/http/source.rs:734]: Is this check not made redundant by the equality check above?

File: proxy/api/src/http/source.rs [hunk 2]
```diff
@@ -729,10 +730,11 @@ mod test {
         })?;
 
         http::test::assert_response(&res, StatusCode::OK, |have| {
-            assert_eq!(have, json!(want));
-            assert_eq!(have.as_array().unwrap().len(), 14);
+            assert_eq!(have["headers"], json!(want.headers));
```
Comment (FintanH) [inline proxy/api/src/http/source.rs:733]: I feel like this test should simply be `assert_eq!(have, json!(want))`, is there a reason for the extra cases?

**Review by FintanH — CHANGES_REQUESTED** [review]

**Comment by rudolfs** [comment]
It seems like the `README.md` is loading twice, causing some flickering.

double-load

File: cypress/integration/project_source_browsing.spec.js [hunk 3]
```diff
@@ -9,14 +9,16 @@ before(() => {
 beforeEach(() => {
   cy.visit("./public/index.html#/profile/projects");
   cy.contains("platinum").click();
+  // Make sure there is enough time to load the commits which refreshes the horizontal menu
+  cy.wait(500);
```
Comment (rudolfs) [inline cypress/integration/project_source_browsing.spec.js:13]: If possible we should avoid fixed `wait`s, because it makes the tests brittle.
A better approach is to check for the presence of an element on screen. This way cypress will wait only as long as necessary and is guaranteed to succeed.

In this case I'd add a `data-cy` to the commit counter and check that the content equals to the number of commits.

Something like: `cy.pick("commit-count").contains("14")`.

File: cypress/integration/project_source_browsing.spec.js [hunk 4]
```diff
@@ -40,6 +42,8 @@ context("commit browsing", () => {
     it("shows the commit history for another branch", () => {
       cy.pick("revision-selector").click();
       cy.get('[data-branch="dev"]').click();
+      // Make sure there is enough time to load the commits
+      cy.wait(500);
```
Comment (rudolfs) [inline cypress/integration/project_source_browsing.spec.js:46]: Ditto.

File: proxy/coco/src/source.rs [hunk 5]
```diff
@@ -185,6 +185,26 @@ impl Serialize for CommitHeader {
     }
 }
 
+/// A selection of commit headers and their statistics.
+pub struct Commits {
```
[the remark this answers is not in the document]
Comment (MeBrei) [reply proxy/coco/src/source.rs:190]: `Serialize` seems enough here. Would it be good to add the others anyway?

File: proxy/api/src/http/source.rs (hunk 2 above)
Comment (MeBrei) [reply proxy/api/src/http/source.rs]: You are right! I just extended the tests without re-thinking the existing ones

File: proxy/coco/src/source.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (FintanH) [reply proxy/coco/src/source.rs:190]: Ya, the others are useful regardless of whether they're needed right now. They're generally useful for debugging tests and what not.

File: proxy/api/src/http/source.rs [hunk 6]
```diff
@@ -691,6 +691,7 @@ mod test {
     }
 
     #[tokio::test]
+    #[allow(clippy::indexing_slicing)]
```
Comment (FintanH) [inline proxy/api/src/http/source.rs:694]:
```suggestion
```

I think this isn't needed now that we cleaned up the testing situation

**Review by FintanH — CHANGES_REQUESTED** [review]

**Comment by MeBrei** [comment]
> It seems like the `README.md` is loading twice, causing some flickering.
> 

@rudolfs I created an issue for this bug #970

**Review by FintanH — APPROVED** [review]
Looks good :+1:

**Review by rudolfs — APPROVED** [review]
